name: Update Visitor Count

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution chaque jour à minuit UTC

jobs:
  update-visitor-count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read current visitor count
        id: read-count
        run: |
          # Extraire la ligne contenant le compteur actuel
          current_count=$(grep -oP '(?<=Total Visits: )\d+' README.md)
          echo "::set-output name=count::$current_count"

      - name: Increment visitor count
        run: |
          # Incrémenter le compteur
          new_count=$(( ${{ steps.read-count.outputs.count }} + 1 ))
          # Remplacer l'ancienne valeur par la nouvelle dans README.md
          sed -i "s/Total Visits: [0-9]*/Total Visits: $new_count/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Mise à jour du compteur de visites : $new_count"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
