name: Update Emoji Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Exécute chaque jour à minuit UTC

jobs:
  update-emoji:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Emoji in README
        run: |
          # Définir les emojis dans un tableau
          emojis=("😎" "😊" "👋")
          # Calculer l'index basé sur le jour (modulo 3 pour cycle)
          day_index=$(( $(date +%j) % 3 ))
          selected_emoji=${emojis[$day_index]}
          # Remplacer l'emoji dans le titre du README
          sed -i "s/Hi .*, I'm Sylvère/Hi $selected_emoji, I'm Sylvère/" README.md

      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Mise à jour de l'emoji du titre : $selected_emoji"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
